//handles registration
export const FULL_NAME_CHANGED = 'FULL_NAME_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const RETYPE_PASSWORD_CHANGED = 'RETYPE_PASSWORD_CHANGED';
export const HANDLE_REGISTRATION_FORM = 'HANDLE_REGISTRATION_FORM';
export const CREATE_USER = 'CREATE_USER';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';

//handles login
export const HANDLE_LOGIN_FORM = 'HANDLE_LOGIN_FORM';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

//get loan details
export const START_FETCH_LOANS = 'START_FETCH_LOANS';
export const GET_ALL_LOANS = 'GET_ALL_LOANS';

//get all the alerts
export const START_FETCH_ALERT = 'START_FETCH_ALERT';
export const GET_ALERT = 'GET_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

//get all the Repayments
export const START_FETCH_REPAYMENTS = 'START_FETCH_REPAYMENTS';
export const GET_ALL_REPAYMENTS = 'GET_ALL_REPAYMENTS';
export const GET_INCOMING_REPAYMENTS = 'GET_INCOMING_REPAYMENTS';
export const GET_OUTGOING_REPAYMENTS = 'GET_OUTGOING_REPAYMENTS';
export const START_UPDATE_REPAYMENT = 'START_UPDATE_REPAYMENT';
export const COMPLETE_UPDATE_REPAYMENT = 'COMPLETE_UPDATE_REPAYMENT';

//handles notification
export const START_FETCH_NOTIFICATION = 'START_FETCH_NOTIFICATION';
export const GET_ALL_NOTIFICATION = 'GET_ALL_NOTIFICATION';
